### ISSUE TITLE
ClickGui CateGory选择时渲染优先级问题

### ISSUE THREAD

**Issue by UknownPerson** [WithoutIQ/OpenFPSMaster#4]
![P 6{KMN0FUW)5K JSD}J{QJ](https://user-images.githubusercontent.com/60729484/186561385-5be59020-fe9f-4e53-8f61-ca086ea5ad09.png)
![Y58KC@F7_)T{ A(ZW}V0SG7](https://user-images.githubusercontent.com/60729484/186561403-f3d01508-f12a-4555-ac9b-d70cb96560c0.png)
解决方法：
可在获取点击位置时存储变量，在下一次渲染时，在遍历category前渲染
或可以遍历两次category，第一次渲染圆角矩形，第二次再渲染字体

**Comment by SuperSkidder** [comment]
clickgui将于不久后重构，故不处理
